import { Inter } from "next/font/google";
import "./globals.css";
import ".//styles/utils.css";
import Sidebar from "@/app/components/Sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full h-full">
      <body className={`${inter.className} w-full h-full`}>
        <main className="w-full h-full bg-background">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
